name: Build and push qcow2 image

on:
  workflow_dispatch:
  ## For testing
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-bush.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: latest

jobs:  
  build-qcow2-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      ARCH: x86_64
    steps:

      - name: Install podman and qemu-utils
        run: |
          sudo apt update
          sudo apt install -y podman qemu-utils

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Pull Image
        id: pull-image
        env:
          INPUT_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        run: |
          sudo podman pull $INPUT_IMAGE

      - name: Bootc image builder
        id: bootc-image-builder
        env:
          INPUT_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          BUILD_DIR: ${{ env.IMAGE_NAME }}/${{ env.TAG }}/${{ env.ARCH }}
        run: |
          mkdir -p $BUILD_DIR
          sudo podman run \
            --rm \
            -it \
            --privileged \
            --pull=newer \
            --security-opt label=type:unconfined_t \
            -v ./config.toml:/config.toml:ro \
            -v ./$BUILD_DIR:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type qcow2 \
            --use-librepo=True \
            --rootfs btrfs
            $INPUT_IMAGE

      - name: Install b2 via python
        run: |
          pip3 install --upgrade b2

      - name: Upload to Backblaze
        id: upload-b2
        env:
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          BUILD_DIR: ${{ env.IMAGE_NAME }}/${{ env.TAG }}/${{ env.ARCH }}
        run: |
          b2 account authorize 2> /dev/null > /dev/null
          b2 sync \
            --threads 4 \
            $BUILD_DIR \
            b2://${{ secrets.B2_BUCKET_NAME }}/artifacts/$BUILD_DIR

  build-qcow2-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    env:
      ARCH: aarch64
    steps:

      - name: Install podman and qemu-utils
        run: |
          sudo apt update
          sudo apt install -y podman qemu-utils

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Pull Image
        id: pull-image
        env:
          INPUT_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        run: |
          sudo podman pull $INPUT_IMAGE

      - name: Bootc image builder
        id: bootc-image-builder
        env:
          INPUT_IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          BUILD_DIR: ${{ env.IMAGE_NAME }}/${{ env.TAG }}/${{ env.ARCH }}
        run: |
          mkdir -p $BUILD_DIR
          sudo podman run \
            --rm \
            -it \
            --privileged \
            --pull=newer \
            --security-opt label=type:unconfined_t \
            -v ./config.toml:/config.toml:ro \
            -v ./$BUILD_DIR:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type qcow2 \
            --use-librepo=True \
            --rootfs btrfs
            $INPUT_IMAGE

      - name: Install b2 via python
        run: |
          pip3 install --upgrade b2

      - name: Upload to Backblaze
        id: upload-b2
        env:
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          BUILD_DIR: ${{ env.IMAGE_NAME }}/${{ env.TAG }}/${{ env.ARCH }}
        run: |
          b2 account authorize 2> /dev/null > /dev/null
          b2 sync \
            --threads 4 \
            $BUILD_DIR \
            b2://${{ secrets.B2_BUCKET_NAME }}/artifacts/$BUILD_DIR