name: Build and push qcow2 image

on:
  workflow_dispatch:
  ## For testing
  push:
    branches: [main]
    paths:
      - ".github/workflows/build-bush.yml"
      - "build/config-img.toml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: alma
  TAG: k3s

jobs:
  build-qcow2:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - arch: amd64
            arch_name: x86_64
            runner: ubuntu-latest
          - arch: arm64
            arch_name: aarch64
            runner: ubuntu-24.04-arm
    env:
      ARCH: ${{ matrix.arch_name }}
    steps:
      - name: Install podman and just
        run: |
          sudo apt update
          sudo apt install -y podman just rclone

      - name: Checkout
        id: checkout
        uses: actions/checkout@v6.0.1

      - name: Build image using justfile
        id: build-image
        run: |
          sudo just build-disk-image ${{ env.IMAGE_NAME }} ${{ env.TAG }}

      - name: Push via Rclone
        run: |
          printf "%s\n" "${{ secrets.RCLONE }}" > /tmp/rclone.conf
          rclone --config /tmp/rclone.conf copyto output/${{ env.IMAGE_NAME }}/${{ env.TAG }}/qcow2/disk.qcow2 b2:github-braccae/artifacts/${{ env.IMAGE_NAME }}-${{ env.TAG }}-$ARCH.qcow2

      # - name: Install b2 via python
      #   run: |
      #     pip3 install --upgrade b2

      # - name: Upload to Backblaze
      #   id: upload-b2
      #   env:
      #     B2_APPLICATION_KEY_ID: ${{ secrets.B2_KEY_ID }}
      #     B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
      #   run: |
      #     b2 account authorize 2> /dev/null > /dev/null
      #     b2 file upload \
      #       --threads 4 \
      #       ${{ secrets.B2_BUCKET_NAME }} \
      #       output/qcow2/disk.qcow2 \
      #       artifacts/coreos-$ARCH.qcow2
